# -*- coding: utf-8 -*-
{
    "name" : "Barcode Labels",
    "version" : "17.0.0.1",
    "category" : "Sales",
    'summary': 'Barcode Labels for All(Products,Templates,Sale,Purchase,Picking)',
    "description": """
            Barcode Labels for All(Products,Templates,Sale,Purchase,Picking)
        """,
    "depends" : ['base','web','sale_management','stock', 'purchase'],
    "data": [
        'security/ir.model.access.csv',
        'data/barcode_config_data.xml',
        'views/barcode_config_views.xml',
        'views/product_view.xml',
        # 'views/product_barcode_report.xml',
        'report/report_barcode_product_labels_temp.xml',
        #'report/report_barcode_product_labels_temp_new.xml',
        'report/report_barcode_product_temp_labels.xml',
        'report/report_barcode_product_temp_labels_new.xml',
        'report/report_barcode_sale_labels.xml',
        'report/report_barcode_sale_labels_new.xml',
        'report/report_barcode_purchase_labels.xml',
        'report/report_barcode_purchase_labels_new.xml',
        'report/report_barcode_stock_labels.xml',
        'report/report_barcode_stock_labels_new.xml',
        'report/report.xml',
        'wizard/barcode_product_labels_view.xml',
        'wizard/barcode_product_temp_labels_view.xml',
        'wizard/barcode_sales_labels_view.xml',
        'wizard/barcode_purchase_labels_view.xml',
        'wizard/barcode_stock_labels_view.xml',
        'wizard/barcode_stock_labels_view_new.xml',
        'wizard/barcode_product_temp_labels_view_new.xml',
        'wizard/barcode_product_labels_view_new.xml',
        'wizard/barcode_sales_labels_view_new.xml',
        'wizard/barcode_purchase_labels_view_new.xml',
        'wizard/barcode_product_temp_labels_view_extra.xml',
        'report/report_barcode_product_temp_labels_extra.xml',
         ],
    "auto_install": False,
    "installable": True,
    "license" : "LGPL-3"
}
