{
    'name' : 'Carrolboyes Custom 14',
    'version' : '1.1',
    'summary': '',
    'sequence': 15,
    'description': """
        Add new fields for product and product template
    """,
    'category': 'Product',
    'website': '',
    'depends' : ['base', 'product', 'stock', 'purchase', 'purchase_stock','crm','account','sale','sale_stock','mrp'], #,'odoo_magento2_ept'],
    'data': [
        'security/product_security.xml',
        'security/ir.model.access.csv',
        'security/account_security.xml',
        'security/crm_security.xml',
        'views/product_art_view.xml',
        'views/product_view.xml',
        'views/report_custom.xml',
        'views/purchase_order.xml',
        'views/crm_team.xml',
        'views/account_move.xml',
        'views/sale_view.xml',
        'views/back_order_menu.xml',
        'views/product_template_view.xml',
        'views/product_main_category_view.xml',      
        'views/product_sub_category_view.xml',   
        'views/product_group_view.xml',      
        'views/product_sub_group_view.xml',
        'views/mrp_order_view.xml',
        'views/stock_view.xml',

    ],
    'demo': [],
    'qweb': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
